version: 2.1

jobs: 
  build:
    docker:
      - image: circleci/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: show current branch
          command: echo ${CURRENT_BRANCH}
      - restore_cache:
          key:
            -app-{{ checksum "package.json" }}
            -app-
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: app-{{ checksum "package.json" }}
  deploy-to-aws-s3:
    docker:
      - image: circle/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: show current branch
          command: echo ${CURRENT_BRANCH}
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudu apt-get install -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r * .[^.]*
            echo "Build Successful"
      - run:
          name: Deploy to AWS S3
          command: |
            if ["CURRENT_BRANCH" == "master"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_PROD_BUCKET} --delete
            elif ["CURRENT_BRANCH" == "staging"]
            then
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_STAGING_BUCKET} --delete
            else ["CURRENT_BRANCH" == "develop"]
              aws --region ${AWS_REGION} s3 sync ~/repo/build s3://${AWS_DEV_BUCKET} --delete
            fi
  deploy-to-aws-cloudfront:
    docker:
      - image: circle/node:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: show current branch
          command: echo ${CURRENT_BRANCH}
      - run:
          name: Installing AWS CLI
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudu apt-get install -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
      - run:
          name: Build Project
          command: |
            npm install
            npm run build
            cd build
            zip ../build.zip -r * .[^.]*
            echo "Build Successful"
      - run:
          name: Deploy to AWS Cloudfront
          command: |
            aws configure set preview.cloudfront
            if ["CURRENT_BRANCH" == "master"]
            then
              aws cloudfront create-invalidation --distribution-id ${PROD_DISTRIBUTION_ID} --path /\*  
            elif ["CURRENT_BRANCH" == "staging"]
            then
              aws cloudfront create-invalidation --distribution-id ${STAGING_DISTRIBUTION_ID} --path /\*
            else ["CURRENT_BRANCH" == "develop"]
              aws cloudfront create-invalidation --distribution-id ${DEV_DISTRIBUTION_ID} --path /\*
            fi        
workflows:
  build_and_deploy:
    jobs: 
      - build
      - deploy-to-aws-s3:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - master    
      - deploy-to-aws-cloudfront:
          requires:
            - build
          filters:
            branches:
              only:
                - develop
                - staging
                - master  